### ISSUE TITLE
[NNBD] Null safety migration

### ISSUE THREAD

**Issue by DevNico** [jifalops/datetime_picker_formfield#106]
Null safety is in beta with flutter core support and it's therefore time to start migrating packages as per the [dart migration guide](https://dart.dev/null-safety/migration-guide).

**Comment by jhb-dev** [comment]
This issue can be closed. The package is migrated to null safety.

See: https://github.com/jifalops/datetime_picker_formfield/commit/daa80936d4d1035c2c7386bd810a7725def786dd and [pub.dev](https://pub.dev/packages/datetime_picker_formfield)
