### ISSUE TITLE
Clearing form field 

### ISSUE THREAD

**Issue by danielc103** [jifalops/datetime_picker_formfield#12]
Clearing form field doesn't trigger onChanged so if setting a value there it sticks.  Should onChanged be triggered for clearing form field or is there another way to clear value?

**Comment by jifalops** [comment]
Clearing the field, by pressing the "X" icon, does trigger `onChange` when I test it. Can you give steps to reproduce? I've also tried specifying its `controller` and calling `controller.clear()`, which seems to work as well.

**Comment by danielc103** [comment]
I've not specified a controller but will try that next. 

After further investigation this doesn't seem to reveal itself on Android, only on iOS. Entering a date triggers, changing a date triggers, but clearing with the "X" button after does not. 

```dart
Widget buildDatePicker() {
    Widget dp = Container(
      padding: EdgeInsets.fromLTRB(0, 50.0, 0, 0),
      child: Row(
        children: <Widget>[
          new Flexible(
              child: DateTimePickerFormField(
            editable: false,
            lastDate: DateTime(DateTime.now().year, DateTime.now().month,
                DateTime.now().day, DateTime.now().hour + 2),
            format: dateFormat,
            dateOnly: true,
            decoration: InputDecoration(
                prefixIcon: Icon(FontAwesomeIcons.calendar),
                labelText: 'Date',
                border: OutlineInputBorder(
                    borderSide: BorderSide(color: Colors.black))),
            onChanged: (dt) {
              print(dt);
              if (dt != null) {
                dateRoch = dt.millisecondsSinceEpoch;
              }
            },
          )),
        ],
      ),
    );

    return dp;
  }
```

**Comment by jifalops** [comment]
From looking at the relevant [lines](https://github.com/jifalops/datetime_picker_formfield/blob/master/lib/datetime_picker_formfield.dart#L244), I am guessing maybe iOS doesn't allow `onChange` to be called if the input isn't focused?

**Comment by chadidi** [comment]
you can user a controller instead (didn't test it yet with this plugin)
```
// create variable
TextEditingController date= new TextEditingController();
// assign varibale to controller
controller: date,
// access the value
date.text
```

**Comment by danielc103** [comment]
I'll try the controller when I get a chance.  I'll close this issue if all is working as expected.
