### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null

### ISSUE THREAD

**Issue by ztrag** [jifalops/datetime_picker_formfield#125]
After flutter upgrade to 3.0.0 the following warning pops up:

```
./../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/datetime_picker_formfield-2.0.0/lib/datetime_picker_formfield.dart:306:20: Warning: Operand of null-aware
operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
```

**Comment by ricardo-hl** [comment]
This error continues

![image](https://user-images.githubusercontent.com/4327356/178065240-5a72ba29-bdc0-42c6-a43b-47c1409b985d.png)
![image](https://user-images.githubusercontent.com/4327356/178065278-ecf5e326-6c20-4d81-b847-26d582e81c37.png)
![image](https://user-images.githubusercontent.com/4327356/178065332-fa88608f-245a-49d2-bc0e-793c3412d213.png)

**Comment by ammarhemani** [comment]
Facing the same error

**Comment by mohhamad-esmaili** [comment]
same here ;/

**Comment by ozhankucuk** [comment]
same error
