### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by ztj666** [jifalops/datetime_picker_formfield#14]

**Comment by jifalops** [comment]
Can you be more specific? I'm not sure what I can do to support Chinese exactly. This widget just combines two platform features together and doesn't introduce anything fundamentally new.

**Comment by ztj666** [comment]
就是怎么设置控件显示中文 现在展示出来默认都是英文

**Comment by jifalops** [comment]
> Is how to set the control to display Chinese. Now the default is English.

The date picker dialog uses https://docs.flutter.io/flutter/material/showDatePicker.html from the platform. I don't see any option for language.

If you mean for the text to be in Chinese, I believe that would be a device setting. 

Here's a couple of resources that might help.
https://github.com/flutter/flutter/wiki/Using-Flutter-in-China
https://stackoverflow.com/questions/50978624/device-language-changes-in-flutter

**Comment by qingxo** [comment]
@jifalops I think the question is, they want to change the "cancel" and "ok" button text when the clock is show on the screen.

**Comment by Wujerry** [comment]
@ztj666  
step1:  
follow this: https://flutter.dev/docs/development/accessibility-and-localization/internationalization

step2:
add ``locale: Locale('zh')``;

example: 
``` 
DateTimePickerFormField(
                  inputType: InputType.both,
                  format: DateFormat('yyyy-MM-dd hh:mm'),
                  editable: false,
                  locale: Locale('zh'),           
                ),
```

**Comment by jifalops** [comment]
Please see the example at https://pub.dev/packages/datetime_picker_formfield#-example-tab-. The last widget at the bottom of the page shows the date/time pickers in Chinese.
