### ISSUE TITLE
DatePicker instead of DateTimePicker

### ISSUE THREAD

**Issue by pacifire** [jifalops/datetime_picker_formfield#15]
Hey Hi...

I need help as: _"I want only DatePicker to be displayed."_
But, DateTimePickerFormField displays Date Picker & Time Picker both.

**Comment by jifalops** [comment]
There is a "dateOnly" option

**Comment by mojason-81** [comment]
I was wanting the "date only" as well.  You can assign the property `dateOnly: true` on the picker.  Here's a link to the source. https://github.com/jifalops/datetime_picker_formfield/blob/master/lib/datetime_picker_formfield.dart#L10
However, you still get a DateTime object so you'll have to monkey with the data if you're wanting to strip out the time component.  I found the `date_format` package helped me here as I only wanted to display a date in my UI.  That package can be found here:  https://pub.dartlang.org/packages/date_format.
I spent a bit of time figuring this out (I'm a perpetual noob), but got what I need/wanted in the end.  Hope this helps!

Oops!  Sorry `@jifalops` for the ping.  Meant to ping @pacifire

**Comment by pacifire** [comment]
@jifalops : Thank you it worked.

**Comment by jifalops** [comment]
@mojason-81 If using `dateOnly`, the time part of the date should be all zeros (beginning of day).

**Comment by mojason-81** [comment]
@jifalops Yes, the time part is all zeros.  For display in the UI, though, I needed to strip the time part off.  Found the `date_format` package worked well for that.

**Comment by jifalops** [comment]
The `dateFormat` parameter should be able to handle that. Im on mobile now
but this may help https://stackoverflow.com/a/50758985/884522. Just don't
include the time parts.

**Comment by mojason-81** [comment]
It doesn't appear to honor the format passed in.
here's my format:
`final _dateFormat = DateFormat('yyyy-MM-dd');`
and here's my use of the widget:
```
ListTile(
    leading: Icon(Icons.calendar_today),
    title: DateTimePickerFormField(
      dateOnly: true,
      format: _dateFormat,
      decoration: InputDecoration(labelText: 'Date'),
      onSaved: (val) => toDoItem.date = val.toString(),
      validator: (val) => null,
    )),
```
and here's the data i'm getting when saving it (as a string)
`"2018-12-13 00:00:00.000"`
I've attempted using different formats such as: `DateFormat('dd M yyyy')` and still get the same format.  I wouldn't be surprised if I'm doing something wrong, but if so, I'm not seeing it.

**Comment by mojason-81** [comment]
Ah!  I think I was being unclear.  The data being *saved* still has the time attached to it.  So when I get that data back from the DB I have to strip the time off of it.  Sorry for the confusion.  I *did* just notice that the time wasn't there when selecting a date.  It's just saving with the time.

**Comment by jifalops** [comment]
It's this line:

```dart
onSaved: (val) => toDoItem.date = val.toString(),
```

You want something like

```dart
onSaved: (val) => toDoItem.date = _dateFormat.format(val),
```

You could also pass the widget a `controller: _textEditingController`, and get the string via `_textEditingController.text`.

Good luck!
