### ISSUE TITLE
Allow timepicker to select minutes

### ISSUE THREAD

**Issue by stt106** [jifalops/datetime_picker_formfield#18]
I see that with `TimePickerFormField` you can manually edit the minutes after selecting the hour, it would be nice to allow selecting both hour and minutes.
Ideally I want to disable editing so that users have to select exactly what they want.

**Comment by jifalops** [comment]
You have to tap on the minutes to change them. This is how Flutter's material design picker works and not something that can be changed by the widget.

**Comment by zaheddec** [comment]
Just came across with onHourDragEnd flag to auto select the minutes.

https://github.com/tjunxiang92/flutter/pull/1/files

This feature will be useful.

Thanks for great plugin.
