### ISSUE TITLE
Date picker crashes when I select the same date. 

### ISSUE THREAD

**Issue by codearemo** [jifalops/datetime_picker_formfield#19]
My datepicker code snippet seems to crash if I select the same date at interval. Say I select 1st January 2019 then click OK...then open  the picker again and select the same date, it crashes.

**Comment by jifalops** [comment]
Can you include the code for the widget?

**Comment by codearemo** [comment]
Okay...sorry I think I fixed it....thanks though

**Comment by jrm86** [comment]
@codearemo, What did you do to fix it?

**Comment by codearemo** [comment]
@jrm86 I handled it in my code to be stored in a List<String> with a max length of 2(one for date and one for time) - according to my code logic. So when I select a date twice it populates the List and then I don't have a time input then my code crashes...so I just made sure the date is not populating the whole list...date has its space...time has its space...Hope you understand
