### ISSUE TITLE
[Q] Why do you need `parent` in constructor?

### ISSUE THREAD

**Issue by vigilancer** [jifalops/datetime_picker_formfield#22]
Hi, 
here you saving widget into state as `parent`:
https://github.com/jifalops/datetime_picker_formfield/blob/942ee5e9f71d65a9c9aae17e3a5d8e2c4312d988/lib/datetime_picker_formfield.dart#L143

You can refer "parent" widget from state with `widget.` notation. Any specific reasons you avoid using it?

**Comment by jifalops** [comment]
Because I didn't know better when I made the widget. #20 fixes this and will be in the next release.

**Comment by vigilancer** [comment]
Got it, thanks!
