### ISSUE TITLE
DateTimePickerFormField overflow on small screens

### ISSUE THREAD

**Issue by georgeherby** [jifalops/datetime_picker_formfield#24]
I am currently running this on a small screen as I am running integration tests on their CI and it's running on an emulator with a small screen (size not confirmed) so I thought I would pick a small screen for a local emulator and then ran the tests and I got the issues with the DateTimePickerFormField. See image of it running on `4  WVGA (Nexus S) API 28` emulator

```
DateTimePickerFormField(
                  editable: false,
                  key: Key("deadline-selector"),
                  validator: (field) {
                    if (field == _createJobController.startDate || field == null) {
                      return "You must enter a future project deadline";
                    } else {
                      return null;
                    }
                  },
                  decoration: InputDecoration(hintText: "Tap to enter project deadline"),
                  initialDate: _createJobController.startDate,
                  firstDate: _createJobController.startDate.add(Duration(days: -1)),
                  dateOnly: true,
                  format: DateFormat("d MMMM yyyy"),
                  onSaved: (newDate) => _createJobController.deadline = newDate)
```

![screenshot_1548944703](https://user-images.githubusercontent.com/21989833/52060645-8c298780-2564-11e9-8ea6-5260da463c66.png)

**Comment by nebnhoj** [comment]
Same Issue with me even though I'm using 6" phone

**Comment by jifalops** [comment]
This appears to be a platform issue https://github.com/flutter/flutter/issues/21383.

You may want to check if `showDatePicker()` does this without this widget.

**Comment by tinoper** [comment]
> This appears to be a platform issue [flutter/flutter#21383](https://github.com/flutter/flutter/issues/21383).
> 
> You may want to check if `showDatePicker()` does this without this widget.
If it helps,I did check with showDatePicker and keyboard doesn't popup. Let me know if you need to test something else.

**Comment by jifalops** [comment]
Closing due to it being fixed upstream
