### ISSUE TITLE
Is it possible to change language on calendar block?

### ISSUE THREAD

**Issue by williamromero** [jifalops/datetime_picker_formfield#26]
I'm a spanish speaker and working on an app with this package, but i want to know if is possible to change the name of the months, days and the action buttons to another languages or is static?

**Comment by jifalops** [comment]
I thought that is what the `locale` parameter is for, or the device's language would be used.  This is related to #14 and may be because of the platform. See https://github.com/flutter/flutter/issues/16304.

**Comment by leonetosoft** [comment]
The problem persists with me, I tried anyway, I need to update to pt_BR,

Can someone help me?

**Comment by jifalops** [comment]
Use the `widgetBuilder` parameter added in 0.2.0.
