### ISSUE TITLE
hour and minute not focus automatically after selecting date

### ISSUE THREAD

**Issue by Basher7** [jifalops/datetime_picker_formfield#27]
When I select date not focusing me automatically to select hours and when i select hour datetime-picker not focusing me automatically in minute selection. To do that I have to prees button every time but I want to do that automatically. Now how could i do this, please help me.
Thank you.

**Comment by Basher7** [comment]
> When I select date not focusing me automatically to select hours and when i select hour datetime-picker not focusing me automatically in minute selection. To do that I have to prees button every time but I want to do that automatically. Now how could i do this, please help me.
> Thank you.

Can anyone help me?

**Comment by jifalops** [comment]
Automatically selecting portions of the date/time is not currently a feature of this widget. Why not use the date/time picker dialogs to select hour/minute?

**Comment by jifalops** [comment]
related to #9

**Comment by tchell** [comment]
FYI this feature was just added to the master branch in flutter with [this pull request](https://github.com/flutter/flutter/pull/31566). If you want the feature immediately then you could switch to master.

**Comment by Basher7** [comment]
Thanks for added this feature

**Comment by Basher7** [comment]
Partially solved. Still now when selecting date it's not automatically focus hour selection.
If possible please try to add. Closing this issue.
Thanks very much @jifalops
