### ISSUE TITLE
Floating labels not working

### ISSUE THREAD

**Issue by lucien-theron** [jifalops/datetime_picker_formfield#28]
As seen on the example the fields have floating labels, how do I achieve this? I copied the example code and its not displaying the floating label on my side.

![image](https://user-images.githubusercontent.com/7767248/53953369-d65dd580-40db-11e9-80b5-af3075e06558.png)

**Comment by jifalops** [comment]
The gif in the readme was made from an older example. The current example sets `hasFloatingPlaceholder: false` on its `InputDecoration`. See below.

```dart
DateTimePickerFormField(
  inputType: inputType,
  format: formats[inputType],
  editable: editable,
  decoration: InputDecoration(
      labelText: 'Date/Time', hasFloatingPlaceholder: false),
  onChanged: (dt) => setState(() => date = dt),
),
```

**Comment by lucien-theron** [comment]
So I would need to set it to true? If I do then I get this:
![image](https://user-images.githubusercontent.com/7767248/55391661-1c228800-553a-11e9-8660-67b309a925b0.png)
