### ISSUE TITLE
Styling colors

### ISSUE THREAD

**Issue by SJente** [jifalops/datetime_picker_formfield#32]
Hey Jifalops,

I'm using your plugin. But because i have themedata with all the colors in my main, the colors in the datetime picker are white just like the background. Now i would love to style it to my own use, i would like to have the numbers show black without using a materialapp because that will destroy my back button. 

Thanks in advance,
Greetings,
J

**Comment by SJente** [comment]
Still facing this issue, using a themedata doesn't even work because the datepicker will take my main themedata. What do i have to do, to make this work?

**Comment by SJente** [comment]
Finally found out how to style it:

```
  new Theme(
                    data: Theme.of(context).copyWith(
                      textTheme: Typography(platform: TargetPlatform.iOS).black,
                    ),
child: DateTimePickerFormField( 
// Here your datepicker stuff
),
),
```

**Comment by jifalops** [comment]
Version 0.2.0 adds a new `widgetBuilder` for this purpose.
