### ISSUE TITLE
overflow error when keyboard open

### ISSUE THREAD

**Issue by peerasun** [jifalops/datetime_picker_formfield#37]
[✓] Flutter (Channel master, v1.5.9-pre.108, on Mac OS X 10.13.6 17G5019, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

Channel master, v1.5.9-pre.108
![BEB454C1-29FE-4352-8AFD-1943CF44444B](https://user-images.githubusercontent.com/8154707/57069438-e02c3f80-6cfe-11e9-8c2e-bd432e17b132.jpg)

**Comment by jifalops** [comment]
Dup of #24
