### ISSUE TITLE
Editing date, keyboard apears

### ISSUE THREAD

**Issue by TheJltres** [jifalops/datetime_picker_formfield#38]
Hi, I get this issue, can you help?

First time I click it works perfectly
![image](https://user-images.githubusercontent.com/23702867/57293293-95c30e00-70c4-11e9-9f69-42f4c50fb08c.png)

I select the Date and save it
![image](https://user-images.githubusercontent.com/23702867/57293318-aa9fa180-70c4-11e9-90c8-6e1726617b71.png)

But when i want to change the date, clicking again, the keyboard raises
![image](https://user-images.githubusercontent.com/23702867/57293351-c3a85280-70c4-11e9-8dc3-236b7610f8a6.png)
![image](https://user-images.githubusercontent.com/23702867/57293423-ffdbb300-70c4-11e9-9aac-0bbcf18167da.png)

Heare is my code
```
return DateTimePickerFormField(
      inputType: InputType.date,
      format: DateFormat('EEEE, dd/MM/yy', 'en_EN'),
      editable: true,
      decoration: InputDecoration(
        icon: Icon(Icons.today),
        labelText: 'Date',
        hintText: '${DateFormat('EEEE, dd/MM/yy').format(DateTime.now())}',
      ),
      dateOnly: true,
      onChanged: (dt) => setState(() => date = dt),
    );
```

Thanks

**Comment by jifalops** [comment]
Set `editable` to `false` to show the picker every time you tap the widget.
