### ISSUE TITLE
Remove print statements from datetime_picker_formfield

### ISSUE THREAD

**Issue by jrm86** [jifalops/datetime_picker_formfield#39]
Request to remove lines [316](https://github.com/jifalops/datetime_picker_formfield/blob/1317954c09c6c3a07be315b4348282b4a1e8944b/lib/datetime_picker_formfield.dart#L316), [323](https://github.com/jifalops/datetime_picker_formfield/blob/1317954c09c6c3a07be315b4348282b4a1e8944b/lib/datetime_picker_formfield.dart#L323), and [330 ](https://github.com/jifalops/datetime_picker_formfield/blob/1317954c09c6c3a07be315b4348282b4a1e8944b/lib/datetime_picker_formfield.dart#L330) of [datetime_picker_formfield.dart](https://github.com/jifalops/datetime_picker_formfield/blob/master/lib/datetime_picker_formfield.dart).

The concern is that these lines send text to the debug console for routine operations under nominal conditions. These messages occur so frequently that actual errors/warnings (such as those on lines [343](https://github.com/jifalops/datetime_picker_formfield/blob/1317954c09c6c3a07be315b4348282b4a1e8944b/lib/datetime_picker_formfield.dart#L343) and [354 ](https://github.com/jifalops/datetime_picker_formfield/blob/1317954c09c6c3a07be315b4348282b4a1e8944b/lib/datetime_picker_formfield.dart#L354), or from other components of an app) may be difficult to find during debugging.

**Comment by jifalops** [comment]
This was fixed in #35 and will be released soon
