### ISSUE TITLE
Focus behavior

### ISSUE THREAD

**Issue by zjelo** [jifalops/datetime_picker_formfield#41]
Focus is behaving funny. On field focus, after leaving, the cursor stays in the field.

![f](https://user-images.githubusercontent.com/41355386/57673107-234db300-761b-11e9-8516-fefe1219e476.jpg)

**Comment by sergeByishimo** [comment]
yeah, i'm getting that too

**Comment by k00na** [comment]
I've managed to overcome this glitch by setting the editable property to false. This then also means that the user wont be able to write data into field, but will be able to get it only from the datepicker dialog. 

BTW, zjelo,I see you're also from slovenia :) Če rabiš kako pomoč pri Flutter-ju, hit me up ;)

**Comment by jifalops** [comment]
This was a bug in 0.1.x. It should be fixed in 0.2.0. Please reopen if it persists.
