### ISSUE TITLE
Keyboard opening although editable is false

### ISSUE THREAD

**Issue by knvpk** [jifalops/datetime_picker_formfield#43]
Im using plugin version 0.2.0.

I have a field where date should only picked up by picker but not the manaual input so i kept editable to false, but still when i clicked the DateTimePickrField keyboard and picker both are opening. My expectation is to open only picker but not the keyboard.

Flutter version: 1.6.3
Android: oreo.

**Comment by knvpk** [comment]
I just checked the example folder provided in plugin code, that also has same behavior.

**Comment by knvpk** [comment]
ping @jifalops

**Comment by knvpk** [comment]
or atleast the `DateTimePickerFormField` field should support the `readOnly` option, for the normal text input if readOnly is true then keyboard not open.

**Comment by tedchuang** [comment]
I think this is a recent Flutter upgrade that caused it. Keyboard did not show up as of June 16, 2019.

**Comment by tedchuang** [comment]
Pull request from @galstc05 works!

**Comment by knvpk** [comment]
Yes, please merge it.

**Comment by NickoftheSouth** [comment]
Just to add to this: this is also and issue when editable is true, since the first time you tap on the field the keybaord pops up and also the picker appears in this squashed form

**Comment by jifalops** [comment]
This is fixed in v0.3.0, but `editable` is now determined by whether `readOnly` is set on its `child`.
