### ISSUE TITLE
Removing render overflow error when keyboard open - Fix not working.

### ISSUE THREAD

**Issue by GrahamDi** [jifalops/datetime_picker_formfield#44]
The code that I believe is intended to correct this issue does not appear to work in my case.

Lines 251 to 255 are as follows:
`    if (MediaQuery.of(context).viewInsets.bottom > 0) {
      FocusScope.of(context).requestFocus(new FocusNode());
      // add a delay just to be sure that keyboard is no longer visible
      await Future.delayed(Duration(milliseconds: 300));
    }
`
The test on 251 always returns 0.0 in my app, I presume because the context is not available? Hence, the delay never runs and I still get the renderflex error.

If I check the value of `MediaQuery.of(context).viewInsets.bottom` immediately before calling DateTimePickerFormField I get a value of 205.0122, if I check it immediately before line 251 in DateTimePickerFormField the value is 0.0

Am I doing something wrong?

**Comment by jifalops** [comment]
This should be fixed in v0.3.0

**Comment by GrahamDi** [comment]
Great.Thanks.
