### ISSUE TITLE
Date Picker not showing after clear or edit

### ISSUE THREAD

**Issue by bottle-rocket-11** [jifalops/datetime_picker_formfield#50]
It seams like the TextField becomes a normal text field after clear or editing of date.  This stops the picker from showing up and I can't select a new date.

**Comment by jifalops** [comment]
I can get this behavior only by editing the date and manually deleting all the characters. I have a fix ready for that but I haven't been able to reproduce the issue using the clear icon/button.

**Comment by winsonet** [comment]
I have the same issue and I found that just need to set it to readonly and will be fixed
