### ISSUE TITLE
how to manage and active only business day?

### ISSUE THREAD

**Issue by sante85** [jifalops/datetime_picker_formfield#53]
Hi,

how to manage and active only business day?

**Comment by jifalops** [comment]
See this SO question https://stackoverflow.com/questions/51683646/how-do-i-use-the-selectabledaypredicate-to-limit-my-datepicker-to-only-weekdays

**Comment by sante85** [comment]
Ok, thanks

Il Gio 25 Lug 2019, 19:05 Jacob Phillips <notifications@github.com> ha
scritto:

**Comment by sante85** [comment]
i have writed code

onShowPicker: (context, currentValue) async {
        return showDatePicker(
            context: context,
            selectableDayPredicate: (DateTime val) =>
            widget.businessDay.length == 0 || widget.businessDay.firstWhere((
                  BusinessDay businessDay) => businessDay.day == val.weekday && businessDay.active) !=
                  null ? true : false
            ,
            firstDate: DateTime.now(),
            initialDate: currentValue ?? DateTime.now(),
            lastDate: DateTime(2100));
      },

but object widget is out of context and not have property businessDay

in onshow picker can you add main context=

**Comment by sante85** [comment]
i want pass a list in 
await widget.onShowPicker(context, value, selectableDayPredicate);

**Comment by sante85** [comment]
even selectableDayPredicate: (DateTime val) => val.weekday==1

throw error
