### ISSUE TITLE
 Error: Method not found: 'DateTimePickerFormField' in flutter x v1.7.8+hotfix.4,

### ISSUE THREAD

**Issue by vivekkujur** [jifalops/datetime_picker_formfield#54]
hi,
iam using  flutter x v1.7.8+hotfix.4,
package installed :   datetime_picker_formfield: ^0.4.0

DateTimePicker is undefined after upgrade flutter from 1.5 to 1.7

error: Error: Method not found: 'DateTimePickerFormField' 
Error: The method 'DateTimePickerFormField' isn't defined for the class

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by jifalops** [comment]
The class was renamed to `DateTimeField` in 0.3.0. The package name is the
same though, and cannot be changed.
