### ISSUE TITLE
Allow datepicker to only select year

### ISSUE THREAD

**Issue by hayribakici** [jifalops/datetime_picker_formfield#56]
Hi, 
thank you for your library. I was wondering, if it is possible to allow the library to only show a year dialog.

Thank you and keep up the nice work.
Cheers.

**Comment by jifalops** [comment]
You could use a dropdown menu for that, or just have them enter the four digit number. But if you want to include this widget, you could use `onShowPicker` to call [`showDialog()`](https://api.flutter.dev/flutter/material/showDialog.html). And present the user with a ListView for instance. As long as you return a `DateTime` from `onShowPicker` it should work.

**Comment by hayribakici** [comment]
hi,

thank you, I'll try it out :)
