### ISSUE TITLE
Update initial time to current time when user tap on the TimePickerFormField

### ISSUE THREAD

**Issue by rupertbulquerin** [jifalops/datetime_picker_formfield#6]
As I noticed, the initial time is not changing after I tap on the timepicker. Let's say I open the app at 2:00 PM and at 2:10 PM when I tap on the timepicker again the initial time is still 2:00PM which I think should be 2:10PM.. How can I set the initial time value when I tap on the timepicker?

**Comment by jifalops** [comment]
This feature has been added to version 0.1.4.
