### ISSUE TITLE
Border colour, default time

### ISSUE THREAD

**Issue by billymahmood** [jifalops/datetime_picker_formfield#60]
Hey,

This is a great package.

I just need help with 2 things please:

1) The Border size is not matching the default border - is there code I can add to change the colour and the thickness of the border?  

2) How do I set a default time?

Thank you

**Comment by jifalops** [comment]
1. I'm not sure about changing the border specifically, but it sounds like you want to use the `builder` argument to `showDatePicker()` (or similar platform method) to override the theme. The [24 hour clock example](https://github.com/jifalops/datetime_picker_formfield/blob/master/example/lib/main.dart#L286) does this.

2. See the line above the link for `initialDate` / `initialTime`.

**Comment by billy124** [comment]
Hi, 


Thank you for your reply, I have attached a screen print to show what I mean by the border, I think it will be possible, I must just be missing something.

Thank you


![WhatsApp Image 2019-08-21 at 08 42 31](https://user-images.githubusercontent.com/4737268/63412498-c9197680-c3ef-11e9-890a-40c1872055e6.jpeg)
