### ISSUE TITLE
Hide input box ?

### ISSUE THREAD

**Issue by raindy29** [jifalops/datetime_picker_formfield#61]
How to hide input box ? use button open to Datepicker  
editable has been removed ?

**Comment by jifalops** [comment]
Use `readOnly` instead of `editable`. The reason being that readOnly was already a property on the underlying TextField.

**Comment by raindy29** [comment]
Thank you for your explanation.
Also set resetIcon: null,but blank replace date text.

![Image 1](https://user-images.githubusercontent.com/10285124/63631230-3aa72e00-c657-11e9-9225-5e4d8887f05a.png)
