### ISSUE TITLE
Please remove ConstrainedBox after date when resetIcon is null

### ISSUE THREAD

**Issue by sandycurrie** [jifalops/datetime_picker_formfield#63]
Would it be possible to remove the ConstrainedBox after the date? It takes up too much space on smaller screens, as per the screenshot below. I could do a Pull Request if you'd like. 

I think the fix would be to change:
`suffixIcon: state.shouldShowClearIcon(effectiveDecoration)
                      ? IconButton(
                          icon: resetIcon,
                          onPressed: state.clear,
                        )
                      : Container(width: 0, height: 0),`
to:
`suffixIcon: state.shouldShowClearIcon(effectiveDecoration)
                      ? IconButton(
                          icon: resetIcon,
                          onPressed: state.clear,
                        )
                      : null,`

![Simulator Screen Shot - iPhone SE - 2019-09-04 at 20 33 02](https://user-images.githubusercontent.com/35437261/64248652-14399a80-cf55-11e9-87e2-790aa5a3d061.png)

**Comment by jifalops** [comment]
Fixed in v0.4.3 / v1.0.0-pre.4
