### ISSUE TITLE
Error: No named parameter with the name 'readOnly'.

### ISSUE THREAD

**Issue by jacksonwilliampluskota** [jifalops/datetime_picker_formfield#66]
hi, when i import the package show this error for me:

Compiler message:
file:///home/jackson/development/flutter/.pub-cache/hosted/pub.dartlang.org/datetime_picker_formfield-0.4.3/lib/datetime_picker_formfield.dart:98:17: Error: No named parameter with the name 'readOnly'.
                readOnly: readOnly,
                ^^^^^^^^
file:///home/jackson/development/flutter/packages/flutter/lib/src/material/text_field.dart:134:9: Context: Found this candidate, but the arguments don't match.
  const TextField({

my flutter version is Flutter 1.5.4
my dart version Dart 2.3.0

**Comment by 98dsky** [comment]
Me Too

**Comment by andrewleesteele** [comment]
Same!

**Comment by markclow** [comment]
Same!

**Comment by jifalops** [comment]
I think this was an upstream issue that has since been fixed.
