### ISSUE TITLE
flutter updated then error is arrived

### ISSUE THREAD

**Issue by undamatlamanikanta** [jifalops/datetime_picker_formfield#69]
Because datetime_picker_formfield 0.4.3 depends on intl ^0.15.8 and no versions of datetime_picker_formfield match >0.4.3 <0.5.0, datetime_picker_formfield ^0.4.3 requires intl ^0.15.8.

**Comment by tinoper** [comment]
Still waiting, let me know if I can help testing something that help with this issue

**Comment by Basher7** [comment]
datetime_picker_formfield pub get failed

Datetime picker formfield pub get failed when I change my intl version 0.15.8 to 0.16.0.
Again staying on intl: ^0.15.8 then pub get failed for flutter_localizations that depends on intl 0.16.0.
I faces this problem when I upgrade flutter version 1.9.1+hotfix.6 to 1.12.13+hotfix.5
how can i overcome this problem, any suggession?

**Comment by jifalops** [comment]
Fixed in v1.0.0
