### ISSUE TITLE
Ability to disable user keyboard entry

### ISSUE THREAD

**Issue by alexZaicev** [jifalops/datetime_picker_formfield#70]
In my app I don`t want to allow user to manually enter some value, instead I want him to always use the dialogs. Unfortunately, the parameters: 
                    _enableInteractiveSelection_  or 
                    _enabled_ 
,does not do the work. This would nice to have as a feature

**Comment by yash-nagdev-sc** [comment]
use editable:false

**Comment by mentoc3000** [comment]
Have you tried `readOnly: true`?

**Comment by alexZaicev** [comment]
@mentoc3000 readOnly disables the field and user cannot tap on it

**Comment by jifalops** [comment]
Tracking in #73
