### ISSUE TITLE
How to style  date picker button text?

### ISSUE THREAD

**Issue by amyuki** [jifalops/datetime_picker_formfield#77]
![image](https://user-images.githubusercontent.com/6037977/71557441-3d8cb200-2a81-11ea-865b-1cd4b1a09949.png)

How can I change these texts color?

**Comment by jifalops** [comment]
This has to do with the platform dialog you are using, not this widget.

**Comment by chitgoks** [comment]
an option to allow adding parameters to let us style buttons.
