### ISSUE TITLE
onChange() not called after date reset

### ISSUE THREAD

**Issue by manugomez95** [jifalops/datetime_picker_formfield#92]
I'm talking about the "X" icon at the right that removes the selected date. I can't find a way to detect this action, and also the field's value remains the same instead of null. Any ideas?

**Comment by rnvitter** [comment]
same issue

**Comment by rnvitter** [comment]
@manugomez95 use the onChange function

**Comment by danielweil** [comment]
It does not trigger onChange event. 
I am having this exact issue.

![image](https://user-images.githubusercontent.com/44274213/98420310-ab244a00-2065-11eb-944b-1f702ac99518.png)
![image](https://user-images.githubusercontent.com/44274213/98420307-a9f31d00-2065-11eb-9c87-c59690bf3f5f.png)
