### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by EmmanuelMess** [jifalops/datetime_picker_formfield#94]
It seems that this library has some performance issues on my LG K11α. It goes below 60fps consistently when I open the date picker.

**Comment by jifalops** [comment]
Good to know. It probably has something to do with the hackish hiding of the keyboard when `readOnly` is false. Otherwise it might just be Flutter-wide. Can you try calling `showDatePicker()` from Flutter and checking?

**Comment by EmmanuelMess** [comment]
Sorry, the issue seems to be a few spikes on the UI thread, with the DatePicker, when I scroll through the months:
![photo5145843074193270932](https://user-images.githubusercontent.com/10991116/85177984-b52ee300-b253-11ea-9bda-3c5a9215daa9.jpg)
